version: "2"
linters:
  # default: all
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    # - clickhouselint
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    # - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    # - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    #- gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    # - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    #- noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unqueryvet
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    # - wrapcheck
    # - wsl
    - wsl_v5
    - zerologlint
  settings:
    ireturn:
      allow:
        - error
        - pulumi.Output
        - KubeSecrets
        - corev1.ConfigMap
        - corev1.SecretState
        - corev1.Secret
        - helm.Release
        - resource.PropertyMap
    revive:
      confidence: 1.0
      # enable-all-rules: false
      # enable-default-rules: false
    funlen:
      ignore-comments: true
    prealloc:
      simple: true
      range-loops: false
      for-loops: false
    varnamelen:
      max-distance: 5
      min-name-length: 3
      check-receiver: false
      check-return: false
      check-type-param: false
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true
      ignore-names:
        - id
        - ok
      ignore-decls:
        - i objLabels []string
        - p PulumiAutoStack
        # - i []struct
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "ST1005:"
      - linters:
        - forcetypeassert
        text: "pulumi"
      - path: unit/base.go
        text: "G101"
        linters:
          - gosec
    paths:
      - unit/base.go
formatters:
  enable:
    # - gci
    # - gofmt
    - gofumpt
    - goimports
run:
  concurrency: 2
  tests: false
  timeout: 5m
