# Edgecase Apparel config file
defaults:
  - &domain edgecase-apparel.app
  - &primaryregion us-mia
  - &stack dev

pulumi:
  context:
    infra: *stack
    kubernetes: *stack
  projects:
    - name: infra-dev
      project: organization/edgecase-apparel-infra
      stack: *stack

# dns
dns:
  domain: *domain
  soa: devrel@akamai.com
  type: master
  ttlSec: 30
  tags:
    - ec-apparel
    - root-dns

# K8s node pools
nodePools:
  apl:
    autoscaler:
      min: 3
      max: 15
    count: 3
    k8sVersion: "1.35"
    label: ec-app-platform
    labels:
      - key: "edgecase-apparel.io/apl"
        value: "true"
    tags:
      - apl
      - ec-apparel
    type: g7-dedicated-16-8
# openbao:
#   count: 3
#   k8sVersion: "1.35"
#   label: ec-openbao
#   labels:
#     - key: "edgecase-apparel.io/openbao"
#       value: "true"
#   tags:
#      - openbao
#      - ec-apparel
#    type: g8-dedicated-16-8

# K8s clusters
lkeClusters:
  primary:  # primary (parent) cluster
    controlPlane:
      auditLogs: true
      highAvailability: true
    k8sVersion: "1.35"
    label: edgecase-apparel-main
    region: *primaryregion
    tags:
      - ec-apparel
      - prod
# standby:
#   controlPlane:
#     auditLogs: true
#     highAvailability: true
#   k8sVersion: "1.35"
#   label: edgecase-apparel-main
#   region: us-mia
#   tags:
#     - ec-apparel
#     - test
#     - dev

appPlatform:
  name: apl-core # name of pulumi resource
  platformName: edgecase-apparel-platform
  domain: *domain
  chart: "apl"
  obj:
    prefix: "ec-apl"
    buckets:
      - loki
      - cnpg
      - harbor
      - thanos
      - tempo
      - gitea
  repo: https://linode.github.io/apl-core
  region: *primaryregion
  valuesTpl: apl-core.tpl
  version: 6.0.0

# more configs go here...