encryptionsalt: v1:bh0XFYACAAQ=:v1:HmfOiYbVdcrkv7W3:5J8NxKqAW5zTqFMrRc/jYcddR8TnJA==
config:
  linode:token:
    secure: v1:SnSx9hV/mflLAIL9:+U02WphVF/F0XMhqGJF2o1qRz2l6GLSStN6rhEnl5k6THubKStfp1cdO3xC1IZFi6UhuwDFnuTdhWz/mWz9Ifj3dxJ10eeevIDwRy0HbuAs=
  edgecase-apparel-kubernetes:kubeSecrets: "true"
