encryptionsalt: v1:Xg5ovRss7ig=:v1:0H8FVli+TiQHgWu5:VF7K2RipsFKfnskh01vwmi5GPe2log==
config:
  linode:token:
    secure: v1:ThzdvdX4pSehdGn9:ljgcJ308fNBGLJFEGvEIrsrHPyjregaKB+hx7OnQAdlVNY6t0nJ81KTtqMY2M0OjWoWbP4Dnw4xV/1gOTyjqRda2Y+1WQhR05xXvUU/97yY=
