schema-version = "1.13.0"


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
go-tools.pkg-path = "go-tools"
golangci-lint.pkg-path = "golangci-lint"
gofumpt.pkg-path = "gofumpt"
go.pkg-path = "go"
go.version = "1.26.1"
adr-tools.pkg-path = "adr-tools"
gnumake.pkg-path = "gnumake"
age.pkg-path = "age"
sops.pkg-path = "sops"
fermyon-spin.pkg-path = "fermyon-spin"

pulumi = { pkg-path = "pulumi", pkg-group = "pulumi-pkg" }
pulumi-language-go = { pkg-path = "pulumiPackages.pulumi-language-go", pkg-group="pulumi-pkg" }

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
KUBECONFIG = "$HOME/.kube/config/edgecase-apparel-main-kubeconfig.yaml"

## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = """
  # Autogenerated by Flox

  # Point GOENV to Flox environment cache
  export GOENV="$FLOX_ENV_CACHE/goenv"
  export GOROOT=

  # Install Go dependencies
  # go get .
  go mod tidy

  # End autogenerated by Flox
  flox gc
"""


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
#common = """
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
#"""
## Shell-specific customizations such as setting aliases go here:
bash = """
  alias isflox='echo yes'
"""
zsh = """
  alias isflox='echo yes'
"""


## Services ---------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## ------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Include ----------------------------------------------------------
## ... environments to create a composed environment
## ------------------------------------------------------------------
[include]
# environments = [
#     { dir = "../common" }
# ]


## Build and publish your own packages ------------------------------
##  $ flox build
##  $ flox publish
## ------------------------------------------------------------------
[build]
# [build.myproject]
# description = "The coolest project ever"
# version = "0.0.1"
# command = """
#   mkdir -p $out/bin
#   cargo build --release
#   cp target/release/myproject $out/bin/myproject
# """


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
# systems = [
#   "aarch64-darwin",
#   "aarch64-linux",
#   "x86_64-darwin",
#   "x86_64-linux",
# ]
# Uncomment to disable CUDA detection.
# cuda-detection = false
